name: Pull Request Target Workflow

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  one:
    runs-on: ubuntu-latest
    environment: pr-e2e-approval
    steps:
      - name: Run one
        run: |
          echo "Run one"

  two:
    runs-on: ubuntu-latest
    environment: pr-e2e-approval
    needs: one
    steps:      
      - name: Run two
        run: |
          echo "Run two..."
